### ISSUE TITLE
Take footer into account

### ISSUE THREAD

**Issue by bashoogzaad** [arthurvaverko/ngx-fill-height#1]
Nice plugin, thanks for that! 

The directive does not take the footer into account in my case, so it fills the entire height and when I scroll the footer appears. Maybe this is a function that will enhance this plugin.

I am open to help you!

**Comment by arthurvaverko-kaltura** [comment]
Yeah that was in the original plugin for angularJS .. I was planning to implement it along with an option to provide and additional custom margin. Ill get to it someday in the meantime feel free to make a pull request

**Comment by arthurvaverko-kaltura** [comment]
i don't know if you saw, i have uploaded a new version introducing footer
support..
